apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket2-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket2
  template:
    metadata:
      labels:
        app: ticket2
    spec:
      containers:
        - name: ticket2
          image: serhii/ticket2:latest
          imagePullPolicy: Never
          env:
            - name: MONGO_URL
              value: 'mongodb://ticket2-mongo-srv:27017/ticket2Project2'
            - name: NATS_URL
              value: 'http://nats2-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  #example: kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: ticket2-srv
spec:
  #type ==> default ClusterIP
  type: ClusterIP
  selector:
    app: ticket2
  ports:
    - name: ticket2
      protocol: TCP
      port: 3000
      targetPort: 3000
